name: 'Terraform'

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform 1.9.7
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.9.7

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Format Check
      run: terraform fmt -check

    - name: Terraform Sec
      uses: aquasecurity/tfsec-action@v1.0.3          
